### PR TITLE
Release 0.7.2

### PR DESCRIPTION
**Pull request by tzumby**

### CODE REVIEW

**Comment by ayrat555** [comment]
hey. it seems it wasn't released yet :cry:

**Comment by tzumby** [comment]
I'm doing this shortly, sorry, busy at ElixirConf all last week :)

**Comment by tzumby** [comment]
@ayrat555 it's published now!

**Comment by ayrat555** [comment]
@tzumby it seems precompiled nifs weren't published :cry:

**Comment by tzumby** [comment]
That's odd, I see them in the CI run: https://github.com/tzumby/ex_keccak/actions/runs/6112378918

I'm doing some digging into this, it's been a while since I pushed the previous version

**Comment by tzumby** [comment]
It's good now, I forgot to download the checksums 🤦

**Pull request merged**
