### PR TITLE
Bump rustler version to 0.23

### PR DESCRIPTION
**Pull request by ayrat555**
Potentially it's breaking change because it's not possible to use two rustler nifs with different ruslter versions

so I think the library should be bumped to `0.3`

```
Failed to use "rustler" (version 0.22.2) because
  ex_keccak (version 0.2.2) requires ~> 0.22.0
  ex_pbkdf2 (version 0.1.0) requires ~> 0.23
  mix.lock specifies 0.22.2
```

### CODE REVIEW

**Comment by ayrat555** [comment]
@tzumby hello! can you please take a look?

**Comment by tzumby** [comment]
Thanks @ayrat555, agreed with the minor version bump 👍

**Comment by ayrat555** [comment]
@tzumby will you do it? or should I create a pr?

**Comment by ayrat555** [comment]
@tzumby https://github.com/tzumby/ex_keccak/pull/23

**Pull request merged**
